# Generated by Django 4.1.7 on 2023-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Şifrə')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyad')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil Şəkli')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'İstifadəçilər',
            },
        ),
    ]
